spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    # creates db in a file called 'monitordb.mv.db'
    url: jdbc:h2:./monitordb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
