server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    # creates db in a file called 'monitordb.mv.db'
    url: jdbc:h2:./scottsoft/db/h2/monitordb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jmx:
    enabled: true
  graphql:
    graphiql:
      enabled: true
